<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
	<Title>Occtoo.Onboarding.Sdk</Title>
	<Company>Occtoo</Company>
	<Authors>Occtoo</Authors>
	<Description>Wrapped HttpClient for onboarding data to Occtoo</Description>
	<Copyright>Copyright © Occtoo AB 2023-</Copyright>
	<PackageTags>occtoo;onboarding</PackageTags>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageIcon>icon.png</PackageIcon>
	<PackageReadmeFile>readme.md</PackageReadmeFile>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<AssemblyVersion>4.0.0.0</AssemblyVersion>
	<FileVersion>4.0.0.0</FileVersion>
	<Version>4.0.0</Version>
	<PackageProjectUrl>https://github.com/Occtoo/Occtoo.Onboarding.Sdk</PackageProjectUrl>
	<RepositoryUrl>https://github.com/Occtoo/Occtoo.Onboarding.Sdk</RepositoryUrl>
	<PackageReleaseNotes>.NET 9 support added</PackageReleaseNotes>
  </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.6.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Collections.Immutable" Version="9.0.5" />
    <PackageReference Include="System.Reactive" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="images\" />
	<None Include="images\icon.png" Pack="true" PackagePath="\" />
	<None Include="docs\readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
